### ISSUE TITLE
Delegated events do not bubble

### ISSUE THREAD

**Issue by kiejo** [ryansolid/dom-expressions#1]
First off, thanks for writing this library! I've been using MobX in combination with React for quite some time and always felt like there must be a more reactive and finer grained approach to updating the DOM with an observer library like MobX. I'm really happy I found your libraries as it looks like they bring it all together in a very nice way. Congrats on your work and the new ideas!

I noticed that setting event handler props that result in delegated events do not bubble, which I assume is not by design. Here is an example:
```javascript
function MyComponent() {
  function onClick(e) {
    console.log(e)    
  }

  return (
    <div onClick={onClick}>
      Parent
      <div onClick={onClick}>
        Child
      </div>
    </div>
  )
}
```
Clicking on the child div prints to the console only once even though `stopPropagation` is not called. Using the `onclick` instead of the `onClick` prop works as expected and clicking on the child div results in two log entries in the console.
I would have expected the delegated events to bubble as long as `stopPropagation` is not called.

**Comment by ryansolid** [comment]
I think that is a fair expectation and I'm going to re-evaluate. The non propagation is sort of intentional. I added this feature to get a number of the VDOM implementors off my back in the JS Frameworks Benchmark. I personally did not see the need for implicit event delegation with this renderer, but by adding I'm committing to support it. And the solution I chose was just copying what some of their libraries do. Unsurprisingly perhaps some of the fastest libraries don't support bubbling delegated events.

I respect InfernoJS balance of performance and capability. I will investigate their solution and likely follow suit on mechanics(although not API).

**Comment by kiejo** [comment]
Thanks for the detailed explanation. It's good to know that the current non propagation is sort of intentional and not a bug, but I'm happy to hear that you are going to re-evaluate the current behavior.

It's obviously not easy to find the right balance between performance and capability, but I think that getting a somewhat more expected (and hopefully useful) behavior might be worth it in this case. Looking forward to further progress on this library!

**Comment by ryansolid** [comment]
Just to update you. Inferno does in fact do event bubbling of delegated events which is good enough for me. I will update this behavior.

**Comment by ryansolid** [comment]
Ok this should behave as expected now in the new version dom-expressions 0.7.10. Please confirm that it works for you.

**Comment by kiejo** [comment]
Wow this was fast! I can confirm that it now works as expected for me.
