### ISSUE TITLE
Hydration checks in dev with mismatched template lengths

### ISSUE THREAD

**Issue by lxsmnsyc** [ryansolid/dom-expressions#159]
I'm currently experiencing the following error and decided to hook into the `template` function
![image](https://user-images.githubusercontent.com/4783372/183292833-1b8624db-db66-434d-8e86-4b3af0ed8c47.png)

It seems that the client template is requesting for 2 more angle brackets (8 is the runtime, 10 is the compile time). Looking into the compiler, the compiler includes the full markup into the equation:

https://github.com/ryansolid/dom-expressions/blob/25ff6ebd0ca894c0b971f46d07cc07126a531bb4/packages/babel-plugin-jsx-dom-expressions/src/dom/template.js#L76-L77

which is contrary to how `template` performs the check only on `innerHTML` and not on `outerHTML` 

https://github.com/ryansolid/dom-expressions/blob/25ff6ebd0ca894c0b971f46d07cc07126a531bb4/packages/dom-expressions/src/client.js#L43

**Comment by ryansolid** [comment]
Hmm yeah browser can't initialize the head.  But this template can never be cloned so it never should get included in the output. We should add head and body to the checks in addition to body since these can never be cloned.

It isn't that the client is trying to innerHTML it just can't put them in a template element.

**Comment by lxsmnsyc** [comment]
I see, so is this a bug on the compiler? or is this resolvable currently?
