### ISSUE TITLE
Example?

### ISSUE THREAD

**Issue by andymans** [ryansolid/dom-expressions#2]
The recent update to make this a generator looks great. An example would be even greater :-)

I've managed to build a runtime using s-js. It only exports a single {wrap} function.

Next I copy that runtime as and use it in a new project 's-jsx/index.js' (using rollup + the babel-jsx.. plugin). 
A simple build where I import
`import S from 's-js';`
`import { wrap } from './s-jsx';`
and run 
`console.log('Hello World')`
works fine...
When I create a "dumb" component (no data just a static message) and use S.root(()=>...)
it also works fine
As soon as I start using S to add some data and render it in my component, it screams out "Can't find variable: r"
Last week, r, root, selectEach and selectWhen would all have been exported by the runtime I built; but no longer. The question is - where's it hiding now?

**Comment by andymans** [comment]
Btw the build on my app is otherwise fantastic! Only 5KB once terser has run...which is excellent!

**Comment by ryansolid** [comment]
Have you updated to the latest version of Babel Plugin JSX DOM Expressions. Part of what makes this work is it no longer uses r. Instead the moduleName option is required and the JSX plugin auto adds the imports.

So if you setup a 's-jsx', you'd want to set it up as:
```js
"plugins": [["jsx-dom-expressions", {moduleName: 's-jsx'}]]
```
What it does is it looks specifically what methods that get used and auto adds the imports to the files. Looking at this now I realize this makes it pretty hard to use a local runtime unless you tell your bundler to resolve path.

Were you using 'solid-js/dom' previously? This library never had selectWhen or selectEach. root is part of S. I realize now it was getting exported as a side effect of how I was Object.assign the runtime. You should still have that S.root.  selectWhen and selectEach I moved from 'solid-js/dom' to 'solid-js' since it was awkward to have the additional import. 

Did you use the cli. I realize I didn't explain the steps well(I've updated the readme). You can copy 'solid-js/dom' again since it would be the same runtime. Then you can copy the other functions from Solid.

I do realize I've made this a whole lot harder as a tradeoff for performance.

**Comment by andymans** [comment]
Aha! That's probably it. I had missed that line in rollup config. Will Change it and re-run. 

To build my custom 'dom-expresions'  (I call it s-jsx') I executed the bin and ran jest. That seemed to do it. A "how to build" would be good tho for ppl new to all this.

To build my actual proj, I'm copying the s-jsx runtime and importing it in my src.directly..

**Comment by andymans** [comment]
Update: just re-ran and now I get a runtime error 'Variable s not found'.

**Comment by andymans** [comment]
OK. I think this is an "understanding" issue on my part. From the readme of this project here is what I understand:

1. I want to build my own custom runtime (that I can then use in other projects)
2. So I cone this repo ('dom-expressions')
3. I make a few tweaks to the dom-expressions.config file
----
At this point the instructions break. Why?
Because it says 'install dom-expressions'. But I've just cloned, and my working dir is now called err "dom-expressions" so that step breaks.
----
In general I think this is an issue faced by bright people everywhere. They've long ago forgotten what it's like NOT to know stuff :-) That make writing docs targeted at a village idiot like me very hard to do :-))

**Comment by ryansolid** [comment]
Ok, right I get the disconnect. The project just changed so fundamentally and only really set it up to serve my purposes. That purpose be authoring libraries. Whereas previously you'd just include it in your project if you wanted.

I was imagining the final target repo say an s-jsx would install it as a dev dependency not clone the repo. So that as part of it's build process it could generate the runtime. And then the final implementor would include that library, not this library as part of their dependencies. The babel Plugin adds import statements to the top of files so it needs to be able to resolve the runtime to a specific relative path or a global path, and being in the node_modules(because the runtime is now just another library) does that pretty much automatically.

It is possible to get this to have everything resolve right with just a file in your project, but you'd need to setup your bundler to resolve the path to that file globally most likely. I'm sure it's doable but I'm not sure how to in each bundler.

**Comment by andymans** [comment]
Finally got it working! Because of the dopey way I'd set up my project I needed to:

`import * as s` from './s-jsx'` (my own custom build of dom-expressions)

and then in rollup-config:

`"plugins": [["jsx-dom-expressions", {moduleName: 's'}]]`

That worked; but obvs was totally brutal. Your new s-jsx repo is far neater!

The value I'm seeing here is that your approach: 
1. can really help people to get off the crack cocaine that is 'virtual dom' 
2. do so without locking themselves into a "framework"
3. allows 1 & 2 with almost zero performance trade-off

Perhaps I can build something with a slightly smaller bundle size, and a little more perf, if I write some optimized (ouch!) vanilla js. BUT - let's say I want to add 'i18n' to my app. How do I do that in vanilla? Well, I need to react EVERY time either my language or my data changes, laboriously executing an update on every element that is affected (pseudocode):

`elem.textContent = You have **count** new count !=1?"messages":"message"`

The alternative in your approach:

`<p>{(i18n('messageCount', state.countOfMessages))}</p>`

...where i18n is a trivially simple function that returns a value from a hash accepting a key and optional count param (if pluralization needed).

Being able to do this is a total "god-send" compared to doing the same in vanilla!

Great work on Solid btw! It's really cool. But I like this lightweight approach too.

**Comment by ryansolid** [comment]
Great I'm glad you got things working. Yeah I mean while it's possible I don't think I'd want to be writing that close to the metal. I still like the declarative format. The best approach to almost Vanilla I've seen is https://github.com/Freak613/stage0, but it isn't for me. Too manual wiring up your own update functions.

I just tried to publish s-jsx just now on npm but it said the name was too similar to a different repo. So I will need to rename it which is awkward since s-jsx is the perfect name. I have no idea what to call it. Atleast you can access it from github for now until I can think of something.
