### ISSUE TITLE
The new html validation cannot be disabled with `validate: false`

### ISSUE THREAD

**Issue by katywings** [ryansolid/dom-expressions#359]
## Is 

Setting `validate: false` in the plugin settings, still shows the `The HTML provided is malformed and will yield unexpected output when evaluated by a browser.
` warnings introduced in #350

## Should

Disabling validation in the plugin settings should hide `The HTML provided is malformed and will yield unexpected output when evaluated by a browser.` warnings.

**Comment by titoBouzout** [comment]
@katywings  I could take a look, but I am not sure if this is going to be a good idea, as malformed html will make solid behave in unexpected ways, throwing random incompressible errors. 

The warning was shown because of missing validation of `th`, which in theory shouldn't have happened. Fix on the way see https://github.com/ryansolid/dom-expressions/pull/360, after that I couldn't think of any other problematic tag, so an error should be an actual error to correct.

**Comment by ryansolid** [comment]
I tend to give escape hatches that shouldn't be used just to help people temporarily deal with false positives. I think in general being able to turn it off is probably a good thing.

**Comment by titoBouzout** [comment]
Agree with that, I will take a look and send a pr, thanks!
