### ISSUE TITLE
Event handler attributes with dashes in them generates invalid syntax

### ISSUE THREAD

**Issue by joakimbeng** [ryansolid/dom-expressions#45]
I'm using [Shoelace](https://shoelace.style) together with Solid and noticed that Shoelace's custom events can't be used because it leads to invalid JavaScript syntax.

Example usage of such Shoelace component and custom event handler:

```tsx
const TitleInput = () => {
  const [title, setTitle] = createSignal("");

  return (
    <sl-textarea
      value={title()}
      onSl-input={(e) => setTitle(e.target?.value)}
    />
  );
};
```

That yields the following syntax:

```js
_el$4.__sl-input = e => setTitle(e.target?.value);
```

And error:

```
SyntaxError: invalid assignment left-hand side
```

Because of the non-quoted `__sl-input` property.

**Comment by ryansolid** [comment]
Is the naming and casing still fine? The reason I ask is the `on___` does some very specific transformations (like lowercases everthing). So if it isn't you might be better off using the [on binding](https://github.com/ryansolid/solid/blob/master/documentation/rendering.md#events) (hopefully to be replaced with namespaces when landing in TS 4.2).

Like:
```jsx
<div on={{ "Weird-Event": e => alert(e.detail) }} />
```
I'm all for turning it into a quoted computed property since that will catch issues like this. I just want to double check it would be doing what you expect.

**Comment by joakimbeng** [comment]
Yes, in this case the event name is "sl-input", so lower casing it and keeping the dash would be fine. And I guess this lib shouldn't generate invalid syntax anyway, as long as the attribute name contains valid characters.

With that said I think the on binding syntax looks better and is more flexible regarding event names, so I'll try that. I hadn't noticed that one in the documentation

Great job with Solid btw! I'm just getting started with it, but on the paper it is the best imo!
