### ISSUE TITLE
document.addEventListener() is called multiple times and registered events are triggered more than once

### ISSUE THREAD

**Issue by chris-czopp** [ryansolid/dom-expressions#53]
This is re: babel-plugin-jsx-dom-expressions v0.25.4 with Solid v0.24.7 

Steps:

- I bundled a module with `delegateEvents` set to true
- I imported this module into an app which is also bundled with `delegateEvents` set to true

The result is that `document.addEventListener()` is called multiple times and registered events are triggered twice (or more depending on the number of imported modules)

Would it be worth somehow scoping what handlers should be triggered within a single bundle? Or making the event handler global?

**Comment by ryansolid** [comment]
I see. So 2 completely separate instances on the same page. Yeah I never gave this scenario any consideration. Obviously sharing the runtime where possible is beneficial, but I can understand where it might not make sense to.

The easiest would be a global. Otherwise we'd need to try shifting the delegated entry which is trickier with Portals and removes the benefit of delegation with web components, or turn the per template compilation and runtime execution like spreads to make the event key writing to be a lookup. Those solutions are technically better as if the nature of these are dynamic and we wanted to do cleanup on global no particular bundle would know if it could. 

Let me see what we can do here.

**Comment by chris-czopp** [comment]
Thanks, it would be very useful for apps which glue multiple self-contained widgets together. Instinctively, I think it would be cool to have a single shared event handler. So, in case of 10 widgets on a single page we'd benefit from event delegation and also there wouldn't be 11 event handlers 😃

**Comment by ryansolid** [comment]
Yeah... cleanup of event delegation is manual. So this seems reasonably at least for now. If I ever made cleanup non-manual I'd need a different solution. I'll go with global for now. Revisit later as needed.
