### ISSUE TITLE
incremental-dom similarities 

### ISSUE THREAD

**Issue by Bnaya** [ryansolid/dom-expressions#6]
First - Thank you very much for all that toolchain
its very impressive :)

I wondering around that field, and i came across your projects and https://github.com/jridgewell/babel-plugin-transform-incremental-dom

And i have a feeling that some of it overlaps, and maybe using [incremental-dom](https://github.com/google/incremental-dom) for the actual dom manipulation can work very nicely with this model 
Have you made any evaluations and comparison of the approaches?

A simple demo of jsx -> incremental dom + mobx:
https://codesandbox.io/s/jsx-incremental-dom-mobx-6ugg1

I'm still trying to wrap my head around how to make granular updates

**Comment by ryansolid** [comment]
That's cool how you pieced that together. I've seen people do similar stuff with other libraries. Take their favourite Reactive library, take a renderer they feel is performant, mix it together and are happy at first, but then wonder if there is more. You have come to the right place.

Incremental DOM while not exactly a typical Virtual DOM library still is based off top down diff/patch scheme found in Virtual DOM libraries. I guess it's more similar to LitHTML in the sense that it diffs against the actual DOM but it is significantly different from what I'm doing here. Incremental DOM still renders down the tree each time diffing the whole tree. You can wrap or trigger that update patch however you see fit. So you can use something like MobX but the granularity will always be coarser. Like at a Component level unless you want to take the overhead on yourself to manage all the template points.

There is nothing wrong with necessarily with doing larger diffs and it's an area I've been experimenting in to find the right balance, but when it comes down to things like lists having to reconcile over and over to update values in the leafs is the same overhead/wasted work you find in Virtual DOM libraries. If done right this can still be pretty fast but it is the advantage of what I'm doing here.

The difference is I'm wrapping at a binding level in many cases. The whole tree doesn't tend to update in on small data updates. Only the things that change. And while I do list reconciliation updating nested values does not require it. In so DOM Expressions is much more performant in those cases which makes it a killer in Benchmarks like the JS Framework Benchmark. I basically made this approach for libraries like MobX. It was hand-tailored with this sort of reactive library in mind.

The down-side is in order to create those separate contexts I need to wrap them in functions. No one wants to do that, so I need to use compilation and in so no runtime approach will not be a bit bulky. I do support HyperScript and Tagged Template Literals but they are worse than the compiled JSX version. With Incremental DOM you will be stuck at that point. The JSX compilation this library does is special. Incompatible with other JSX libraries as it doesn't compile to HyperScript variants. It makes things like TypeScript a challenge at times (but we are getting there). But I think it will be challenging to find a rendering approach better suited to libraries like MobX. 

For me it was Knockout that got me into this and I wrote this initially to see if I could put reactive libraries back on top of the performance spectrum. In the process, I realized that almost all these libraries were the same so I generalized it so all libraries like this including MobX could benefit. And I wrote my own higher performance (and opinionated) reactive library Solid to showcase it to the extreme, both in performance and React feature parity.

I hope that answers the questions. And feel free to shoot me more. I have a lot of articles linked off the bottom of Solid's readme about Solid mostly but since it's the same reactive core they apply to all libraries based on DOM Expressions.

**Comment by Bnaya** [comment]
Its all super interesting,
I will keep an eye over solid
