### ISSUE TITLE
component HydrationScript allow adding attributes to script tag

### ISSUE THREAD

**Issue by beckend** [ryansolid/dom-expressions#76]
I would like to add defer so I do not need to move the script to the end of the body.

**Comment by ryansolid** [comment]
I need to consider how to do this since there is a bit of out of order thing happening with creation. I see the benefit of supporting this as long as people are careful that it runs before any of their application scripts.

I believe defer'd scripts will run in order so as long as it happens before the main script (probably type="module" so will be deferred by default) I think that is still good. There is some complications with streaming which is better to run async if possible. Which means you'd want hydration script to probably run as soon as possible.

In either case should look at a generic way to support augmenting the script tags (more than the nonce, I have now) and worry about that as the situation arises.

**Comment by ryansolid** [comment]
Hmm.. on inspection I found this: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script#attr-defer
It looks like `defer` has no effect on inline scripts. Other than `nonce` I'm not sure if any of the other attributes are relevant.

**Comment by beckend** [comment]
Good catch, I leave it to you.
